on:
    workflow_dispatch:

    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                bun-version: latest

            - name: Install Modules and Build
              run: |
                bun compileApps.js ${{ github.sha }}
                bun makeListfile.js
                cp dist/README.md ./README.md

            - name: Push to Dist
              uses: s0/git-publish-subdir-action@develop
              env:
                REPO: self
                BRANCH: dist
                FOLDER: dist
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                MESSAGE: "[`{sha}`] {msg}"
            - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
              with:

                add: 'src'
                cwd: '.'
                fetch: false
                message: 'updated readme'
                pathspec_error_handling: ignore
                pull: ''
                push: true
         
